my_tips_and_tricks/config/routes.rb
Rails.application.routes.draw do
  get 'cities/new'
  # --- Sessions routes --
  resources :sessions, only: [:new, :create, :destroy]
  
  # --- Route for home ---
  root 'gossips#index'
  
  # --- Routes for about_us_controller ---
  get '/contact', to: 'about_us#contact'
  get '/team', to: 'about_us#team'
  
  # --- Routes for gossip_controller ---
  get '/welcome/:user', to: 'gossips#welcome', as: 'welcome'
  resources :gossips
  
  # --- Routes for user controller ---
  resources :users

  # --- Routes for city controller ---
  resources :cities
  
  # --- Routes for comment controller ---
  resources :gossips do
    resources :comments
  end

  # --- Routes for likes controller
  resources :gossips do
    resources :likes
  end
end

my_tips_and_tricks/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my_tips_and_tricks/app/models/city.rb
class City < ApplicationRecord
  # --- Associations --
  has_many :users

  # --- Validations ---
  validates :name,
    presence: true
  
  validates :zip_code,
    presence: true
    # ,
    # format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, 
    #           message: "please enter a valid french zip code" }
  
  validates :name,
    uniqueness: { scope: :zip_code, message: 'City already exist' }
end

my_tips_and_tricks/app/models/comment.rb
class Comment < ApplicationRecord
  # --- Associations ---
  belongs_to :gossip
  belongs_to :user
end

my_tips_and_tricks/app/models/gossip.rb
class Gossip < ApplicationRecord
  # --- Associations ----
  belongs_to :user
  has_many :gossips_tags
  has_many :tags, through: :gossips_tags
  has_many :comments
  has_many :likes

  # --- Validatins ---
  validates :title,
    presence: true,
    length: { in: 3..14, 
      too_short: " must have at least %{count} characters",
      too_long: " must have at most %{count} characters"
    }

  validates :content,
    presence: true

  # --- Instance methods ---
  def comments_count
    self.comments.count
  end

  def like_of(user)
    Like.find_by(user_id: user.id, gossip_id: self.id) if user
  end
end

my_tips_and_tricks/app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

my_tips_and_tricks/app/models/like.rb
class Like < ApplicationRecord
  # --- Associations ---
  belongs_to :user
  belongs_to :gossip

  # --- Validations ---
  validates :user_id,
    uniqueness: { scope: :gossip_id, message: 'already liked' }
end

my_tips_and_tricks/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

my_tips_and_tricks/app/models/tag.rb
class Tag < ApplicationRecord
  # --- Associations ---
  has_many :gossips_tags
  has_many :gossips, through: :gossips_tags

  # --- Validations ---
  validates :title,
    presence: true,
    length: { in: 3..14 }
end

my_tips_and_tricks/app/models/user.rb
class User < ApplicationRecord
  # --- Security ---
  has_secure_password

  # --- Associations ---
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes

  # --- Validations ---
  validates :first_name,
    presence: true
  
  validates :last_name,
    presence: true
  
  validates :age,
    numericality: { greater_than: 0 }
  
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "wrong format!" }
  
  validates :password,
    presence: true,
    length: { minimum: 6 }
end

my_tips_and_tricks/app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
end

my_tips_and_tricks/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @like = Like.new
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      flash[:success] = 'City successfully created.'
      redirect_to new_user_path
    else
      render :new
    end
  end

  private
  def city_params
    params.require(:city).permit(:name, :zip_code)
  end
end

my_tips_and_tricks/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user

  def create
    @comment = Comment.create(comment_params.merge(user: current_user))
    redirect_to gossip_path(params[:gossip_id])
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to gossip_path(params[:gossip_id])
  end
  
  def destroy
    Comment.destroy(params[:id])
    redirect_to gossip_path(params[:gossip_id])
  end
  
  private
  def comment_params
    content = params.permit(:content)[:content]
    gossip_id = params.permit(:gossip_id)[:gossip_id]
    {content: content, gossip_id: gossip_id}
  end
end

my_tips_and_tricks/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  
  def welcome
    @user = params[:user]
  end
  
  def index
    @gossips = Gossip.all
    @like = Like.new
  end
  
  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @like= Like.new
  end
  
  def new
    @gossip = Gossip.new
  end
  
  def create
    @gossip = Gossip.new(gossip_params.merge(user: current_user))
    if @gossip.save
      flash[:success] = "Gossip successfullty created."
      redirect_to root_path
      # render template: 'others/successful_creation', locals: {class_name: @gossip.class}
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if is_gossip_author?(@gossip)
      if @gossip.update(gossip_params)
        redirect_to @gossip
      else
        render :edit
      end
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if is_gossip_author?(@gossip)
      @gossip.destroy
      redirect_to root_path
    end
  end
  
  private
  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

my_tips_and_tricks/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    gossip_id = params.permit(:gossip_id).require(:gossip_id)
    @like = Like.new(user_id: current_user.id, gossip_id: gossip_id)
    flash[:danger] = @like.errors.full_messages.join(' ') if !@like.save
    redirect_back fallback_location: root_path
  end
  
  def destroy
    like_id = params.permit(:id).require(:id)
    Like.destroy(like_id)
    redirect_back fallback_location: root_path
  end
end

my_tips_and_tricks/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @cities = City.all
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:danger] = "User successfully created."
      log_in(@user)
      redirect_to root_path
    else
      @cities = City.all
      render :new
    end
  end
  
  private
  def user_params
    u_params = params.require(:user).permit(:first_name, :last_name, :email, :age, :description, :password, :password_confirmation)
    u_city_param = params.permit(:city_id)
    u_params.merge(u_city_param)
  end
end

my_tips_and_tricks/app/helpers/about_us_helper.rb
module AboutUsHelper
end

my_tips_and_tricks/app/helpers/application_helper.rb
module ApplicationHelper
end

my_tips_and_tricks/app/helpers/cities_helper.rb
module CitiesHelper
end

my_tips_and_tricks/app/helpers/comments_helper.rb
module CommentsHelper
end

my_tips_and_tricks/app/helpers/gossip_helper.rb
module GossipHelper
end

my_tips_and_tricks/app/helpers/likes_helper.rb
module LikesHelper
end

my_tips_and_tricks/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged?
    !current_user.nil?
  end

  def authenticate_user
    unless logged?
      flash[:danger] = "Please login."
      redirect_to new_session_path
    end
  end

  def is_gossip_author?(gossip)
    current_user.id == gossip.user_id
  end

  def is_comment_author?(comment)
    current_user.id == comment.user_id
  end

  def like(gossip_id, user_id)
    Like.like(gossip_id, user_id)
  end
end

my_tips_and_tricks/app/helpers/user_helper.rb
module UserHelper
end

my_tips_and_tricks/app/views/cities/new.html.erb
<div class="container-fluid mt-3">
<p>You can create a new city here.</p>
<%= form_for @city do |f| %>
  <div class="form-group row">
    <div class="col-xs col-sm-6 col-md-4">
      <%= f.label 'name', 'Name :', class: 'col-form-label' %>
      <%= f.text_field :name, class: 'form-control form-control-sm' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-xs col-sm-6 col-md-4">
      <%= f.label 'zip_code', 'Zip code :' %>
      <%= f.text_field :zip_code, class: 'form-control form-control-sm' %>
    </div>
  </div>
  <%= submit_tag 'Create', class: 'btn btn-info btn-sm mt-3' %>
<% end %>

<% if @city.errors.any? %>
  <div class="alert alert-danger mt-3 w-75">
    <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

my_tips_and_tricks/app/views/cities/show.html.erb
<div class="container-fluid mt-3">    
  <div class="row">
    <div class="col-xs col-md-3" style="height: 100px">
      <div class="card shadow-sm p-0">
        <div class="card-body alert alert-danger mt-3 mb-0">
          <h5 class="card-title text-center font-weight-bold"><%= @city.name %></h5>
          <p class="card-text text-center"><span class="font-weight-bold">Zip code :</span> <%= @city.zip_code%></p>
        </div>
      </div>
    </div>
    <div class="col-xs col-md-9">
      <% @city.users.each do |user| %>
        <% user.gossips.each do |gossip| %>
          <div class="row mb-3">
            <div class="col-xs col-sm-3 mb-2 mb-sm-0">
              <div class="card shadow-sm d-flex flex-column justify-content-center align-items-center h-100 p-1">
                <div class="body">
                  <p class="card-text text-center"><%= user.first_name %> <%= user.last_name %></p>
                </div>
                <%= image_tag "team/identity-photo.jpg", class: "img-circular", height: "80px", width: "80px" %>
              </div>
            </div>
            <div class="col-xs col-sm-9">
              <div class="card shadow-sm h-100">
                <div class="card-header text-uppercase alert alert-info">
                  <%= gossip.title %>
                </div>
                <div class="card-body pt-0 pb-1">
                  <p class="card-text"><%= gossip.content %></p>
                  <div class="d-flex flex-row justify-content-between align-items-center" style="width: 75px">
                    <div class="badge badge-primary h-50" style="width: 25px"><%= gossip.likes.count %></div>
                    <!--<%= link_to "Like", gossip_likes_path(gossip.id), method: 'post', class: 'badge badge-warning' %>-->
                    <% if logged? %>
                      <% if !gossip.like_of(current_user) %>
                        <%= form_for Like.new, url: gossip_likes_path(gossip.id) do |f| %>
                          <input type="hidden" name="gossip_id" value=<%= gossip.id %> >
                          <button type="submit" class="btn btn-warning badge badge-warning">Like</button>
                        <% end %>
                      <% else %>
                        <%= form_for @like, url: gossip_like_path(gossip.id, gossip.like_of(current_user).id), method: :delete do |f| %>
                          <button type="submit" class="btn btn-danger badge badge-danger">Unlike</button>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

my_tips_and_tricks/app/views/gossips/edit.html.erb
<div class="container-fluid mt-3">
  <p>Here you can edit the gossip.</p>
  <%= form_for @gossip do |f| %>
    <div class="row">
      <div class="col-xs col-sm-3">
        <div class="form-group">
          <div>
            <label for="title" class="col-form-label">Title : </label>
            <%= f.text_field :title, class: "form-control form-control-sm" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs col-md-6">
        <div class="form-group">
          <div>
            <label for="content" class="col-form-label">Content : </label>
            <%= f.text_area :content, rows: 5, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
    <%= submit_tag "Update", class: "btn btn-info btn-sm" %>
  <% end %>

  <% if @gossip.errors.any? %>
    <div class="mt-3 alert alert-danger">
      <p>Gossip creation faild for the following reason(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %>.</li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

my_tips_and_tricks/app/views/gossips/index.html.erb
<div class="container-fluid position-absolute mt-4">
  <div class="jumbotron p-0 mb-3">
    <%= image_tag 'index/tipstricks.png', class: 'img-responsive w-100' %>
  </div>
  <p class="h4 font-weight-bold mb-3" style="font-size: 3vh; ">Hi there ! These are all tips and tricks.</p>
  <p class="mb-3">You too can make a tips and tricks. <%= link_to "Do it here !", new_gossip_path, style: "text-decoration: none" %></p>
  <div class="row">
    <% @gossips.each do |gossip| %>
    <div class="col-xs col-sm-6 col-lg-4 mb-3">
      <div class="card">
        <div class="card-header alert alert-success">
          <h5><span class="font-weight-bold">Title : </span><%= gossip.title %></h5>
        </div>
        <div class="card-body pt-0">
          <div>
            <p class="card-text"><span class="font-weight-bold">Author : </span><%= gossip.user.first_name %> <%= gossip.user.last_name %>, from <a href="<%= city_path(gossip.user.city.id) %>" class="badge badge-danger"><%= gossip.user.city.name %></a></p>
          </div>
          <p class="text-primary mt-3"><%= gossip.comments_count %> comments</p>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <%= link_to "Go to tip and trick page", gossip_path(gossip.id), class: "btn btn-info" %>
            <div class="d-flex flex-column flex-sm-row justify-content-between align-items-center">
              <div class="badge badge-primary h-50 mr-1" style="width: 25px"><%= gossip.likes.count %></div>
              <!--<%= link_to "Like", gossip_likes_path(gossip.id), method: 'post', class: 'badge badge-warning' %>-->
              <% if logged? %>
                <% if !gossip.like_of(current_user) %>
                  <%= form_for Like.new, url: gossip_likes_path(gossip.id) do |f| %>
                    <input type="hidden" name="gossip_id" value=<%= gossip.id %> >
                    <button type="submit" class="btn btn-warning badge badge-warning">Like</button>
                  <% end %>
                <% else %>
                  <%= form_for @like, url: gossip_like_path(gossip.id, gossip.like_of(current_user).id), method: :delete do |f| %>
                    <button type="submit" class="btn btn-danger badge badge-danger">Unlike</button>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

my_tips_and_tricks/app/views/gossips/new.html.erb
<div class="container-fluid mt-3">
  <p>You want to create a tip and trick. You can do it now !</p>
  <%= form_for @gossip do |f| %>
    <div class="row">
      <div class="col-xs col-sm-3">
        <div class="form-group">
          <div>
            <label for="title" class="col-form-label">Title : </label>
            <%= f.text_field :title, class: "form-control form-control-sm" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs col-md-6">
        <div class="form-group">
          <div>
            <label for="content" class="col-form-label">Content : </label>
            <%= f.text_area :content, rows: 5, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
    <%= submit_tag "Send", class: "btn btn-info btn-sm" %>
  <% end %>

  <% if @gossip.errors.any? %>
    <div class="mt-3 alert alert-danger">
      <p>Gossip creation faild for the following reason(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %>.</li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

my_tips_and_tricks/app/views/gossips/show.html.erb
<div class="jumbotron alert alert-info mt-3">
  <% if logged? && is_gossip_author?(@gossip) %>
    <div class="d-flex flex-row justify-content-center">
      <%= link_to "Edit", edit_gossip_path(@gossip.id), class: "btn btn-warning btn-sm mr-2", style: "text-decoration: none" %>
      <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger btn-sm ml-2" style="text-decoration: none" data-confirm="Are you sure !" data-method="DELETE">
        Delete
      </a>
    </div>
  <% end %>

  <h1 class="text-uppercase font-weight-bold"><%= @gossip.title %></h1>
  <p class="lead"><%= @gossip.content %></p>
  <hr class="my-4">
  <p class="mb-3"><span class="h4 font-weight-bold"><%= @gossip.user.first_name %> <%= @gossip.user.last_name %></span> <span class="h6">from</span> <a href="<%= city_path(@gossip.user.city.id) %>" class="badge badge-danger" style="text-decoration: none"><%= @gossip.user.city.name %></a></p>
  <p class="h6"><span class="font-weight-bold">Email : </span><%= @gossip.user.email %></p>
  <p class="h6"><span class="font-weight-bold">Age : </span><%= @gossip.user.age %> years</p>
  <p class="h6"><span class="font-weight-bold">Description : </span><%= @gossip.user.description %></p>
  <div class="d-flex flex-row justify-content-between align-items-center">
    <%= link_to "Show author details", user_path(@gossip.user.id), class: "btn btn-primary btn-md mt-2", style: "text-decoration: none"%>
    <div class="d-flex flex-row justify-content-between align-items-center" style="width: 75px">
      <div class="badge badge-primary h-50" style="width: 25px"><%= @gossip.likes.count %></div>
      <!--<%= link_to "Like", gossip_likes_path(@gossip.id), method: 'post', class: 'badge badge-warning' %>-->
      <% if logged? %>
        <% if !@gossip.like_of(current_user) %>
          <%= form_for Like.new, url: gossip_likes_path(@gossip) do |f| %>
            <input type="hidden" name="gossip_id" value=<%= @gossip.id %> >
            <button type="submit" class="btn btn-warning badge badge-warning">Like</button>
          <% end %>
        <% else %>
          <%= form_for @like, url: gossip_like_path(@gossip.id, @gossip.like_of(current_user).id), method: :delete do |f| %>
            <button type="submit" class="btn btn-danger badge badge-danger">Unlike</button>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% if @gossip.comments.count != 0 %>
  <div class="card">
    <div class="card-header alert alert-info h5 mb-0">
      These are all the comments for this gossip :
    </div>
    <ul class="list-group list-group-flush">
      <% @gossip.comments.each do |comment| %>
        <li class="list-group-item py-0 d-flex flex-row justify-content-between align-items-center">
          <div class="mt-3">
            <p class="text-card"><%= comment.content %></p>
            <p class="text-card">by : <span class="text-danger font-weight-bold"><%= comment.user.first_name %> <%= comment.user.last_name %></span></p>
          </div>
          <% if !logged? || is_comment_author?(comment) %>
            <div>
              <a class="btn btn-warning btn-sm" href=<%= edit_gossip_comment_path(@gossip.id, comment.id) %>>Manage</a>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container-fluid mt-3">
  <%= form_tag gossip_comments_path(@gossip.id) do %>
    <div class="row">
      <div class="col-xs col-md-6">
        <div class="form-group">
          <div>
            <%= label_tag 'content', "You can make some comments here !", class: "col-form-label" %>
            <%= text_area_tag 'content', @comment.content, rows: 3, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
    <%= submit_tag "Add Comment", class: "btn btn-info btn-sm"%>
  <% end %>
</div>

my_tips_and_tricks/app/views/gossips/welcome.html.erb
<div class="container-fluid d-flex flex-column justify-content-center align-items-center mt-4 bg-light">
  <h2 class="text-center font-weight-bold">Welcome <%= @user %> !</h2>
  <p class="text-center">This is our tips and tricks website. Here you can post, comment and show tips and tricks.</p>
  <%= link_to "Click to view our beautiful tips and tricks !", root_path, style: 'text-decoration: none' %>
</div>

my_tips_and_tricks/app/views/users/new.html.erb
<div class="container-fluid mt-3">
  <p>Hi there, fill in the form and join us !</p>
  <%= form_for @user do |f| %>
    <div class="row">
      <div class="col-xs col-sm-6 col-md-4">
        <div class="form-group">
          <div>
            <%= f.label 'first_name', 'First name :', class: 'col-form-label' %>
            <%= f.text_field :first_name, class: "form-control form-control-sm" %>
          </div>
        </div>
      </div>
      <div class="col-xs col-sm-6 col-md-4">
        <div class="form-group">
          <div>
            <%= f.label 'last_name', 'Last name :', class: 'col-form-label' %>
            <%= f.text_field :last_name, class: "form-control form-control-sm" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs col-sm-6 col-md-4">
        <div class="form-group">
          <div>
            <%= f.label 'email', 'Email : ' %>
            <%= f.text_field :email, class: "form-control form-control-sm" %>
          </div>
        </div>
      </div>
      <div class="col-xs col-sm-3">
        <div class="form-group">
          <div>
            <%= f.label 'age', 'Age : ' %>
            <%= f.text_field :age, class: "form-control form-control-sm" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs col-md-6">
        <div class="form-group">
          <div>
            <%= f.label 'description', 'Description :', class: 'col-form-label' %>
            <%= f.text_area :description, rows: 3, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs col-sm-6 col-md-4">
        <div class="form-group">
          <%= f.label 'city_id', 'City : ' %>
          <%= select_tag 'city_id', options_for_select(@cities.collect { |u| [u.name, u.id] }), prompt: 'Please select a city', class: 'form-control form-control-sm' %>
        </div>
      </div>
      <div class="col-xs col-sm-6 pt-sm-3">
        <%= link_to "Create a new city", new_city_path, class: 'btn btn-info btn-sm mt-sm-3 mb-3' %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs col-sm-6 col-md-4">
        <div class="form-group">
            <%= f.label 'password', 'Password : ', class: 'col-form-label' %>
            <%= f.password_field :password, class: "form-control form-control-sm" %>
        </div>
      </div>
      <div class="col-xs col-sm-6 col-md-4">
        <div class="form-group">
            <%= f.label 'password_confirmation', 'Password confirmation :', class: 'col-form-label' %>
            <%= f.password_field :password_confirmation, class: "form-control form-control-sm" %>
        </div>
      </div>
    </div>
    <%= submit_tag "Sign up", class: "btn btn-info btn-sm" %>
  <% end %>

  <% if @user.errors.any? %>
    <div class="mt-3 alert alert-danger">
      <p>User creation faild for the following reason(s) :</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %>.</li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

my_tips_and_tricks/app/views/users/show.html.erb
<div class="container-fluid position-absolute mt-4">
  <h3 class="text-center font-weight-bold">User informations</h3>
  <div class="row d-flex justify-content-center">
    <div class="col-xs">
      <div class="card shadow-sm alert alert-primary">
        <div class="card-body">
          <h5 class="card-title text-center font-weight-bold"><%= @user.first_name %> <%= @user.last_name %></h5>
          <h5 class="card-title text-center"><span class="badge badge-danger"><%= @user.email %></span></h5>
          <h6 class="card-text text-center"><%= @user.age%> years old</h6>
          <h6 class="card-text text-center"><span class="font-weight-bold">from :</span> <%= @user.city.name%></h6>
          <p class="card-text text-center"><%= @user.description%></p>
        </div>
      </div>
    </div>
  </div>
</div>