Kitty-Project-V2/config/routes.rb
Rails.application.routes.draw do
  get 'provisional_cart_items/index'
  get 'provisional_cart_items/create'
  root 'items#index'
  
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, except: [:show, :edit]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  
  resources :orders

  resources :items
  
  resources :cart_items, only: [:index, :update, :destroy]
  resources :items do 
    resources :cart_items, only: [:create]
  end

  resources :provisional_cart_items, only: [:index, :update, :destroy]
  resources :items do
    resources :provisional_cart_items, only: :create
  end
  
  resources :categories do
    resources :items
  end
  
  resources :items, only: [:show] do
    resources :images, only: [:create]
  end

  # Add pesonalized routes
  get '/mon_panier', to: 'carts#show', as: 'mon_panier'
  get '/mon_profil', to: 'users#show', as: 'mon_profil'
  get '/editer_mon_profil', to: 'users#edit', as: 'editer_mon_profil'
  get '/contact', to: 'carts#contact'
end

Kitty-Project-V2/app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Relationship
  belongs_to :cart 
  belongs_to :item
end

Kitty-Project-V2/app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart = current_user_cart
    @cart_items = @cart.cart_items.sort_by(&:created_at)
    
    @total_quantities = current_user_cart_items_count
    @total = current_user_cart_total
  end
  
  def create
    @item = Item.find(permitted_item_id_param)
    params = {item: @item, cart: current_user_cart}

    if CartItem.exists?(params)
      CartItem.find_by(params).increment!(:quantity)
    else
      @cart_item = CartItem.create(params)

      if @cart_item.valid?
        # flash[:notice] = 'Un produit a été ajouté à votre panier !'
      else
        # flash[:alert] = purify_message(@cart_item.errors.full_messages.to_sentence)
      end
    end
    
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js { }
    end
  end

  def update
    cart_item = CartItem.find(permitted_cart_item_id_param)
    cart_item.update(quantity: permitted_item_quantity_param)

    @total_quantities = current_user_cart_items_count
    @total = current_user_cart_total
  end
  
  def destroy
    @cart_item_id = params[:id]
    CartItem.destroy(@cart_item_id)
    
    respond_to do |format|
      format.html { redirect_to cart_items_path }
      format.js { }
    end
  end

  private

  def permitted_item_id_param
    params.permit(:item_id).require(:item_id)
  end

  def permitted_cart_item_id_param
    params.permit(:id).require(:id)
  end  
  
  def permitted_item_quantity_param
    params.permit(:quantity).require(:quantity)
  end
end

Kitty-Project-V2/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

Kitty-Project-V2/app/views/cart_items/_picture_indicating_empty_cart.html.erb
<div id="empty-img" class="texte-bienvenue text-center">
  <br>
  <h2>Vous n'avez aucun produit dans votre panier !</h2> <br>
  <img src = https://images.pexels.com/photos/127027/pexels-photo-127027.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 style="height: 500px;" >
  <br>
  <br>
  <a class="btn btn-secondary text-decoration-none" href="/">Revenir à l'accueil</a>
  <br>
  <br>
</div>

Kitty-Project-V2/app/views/cart_items/create.js.erb
itemId = <%= @item.id %>;
addItemBtn = $('div#' + itemId + '-add-to-cart-btns-container > a.btn');
addItemBtn.blur();

document.getElementById("items-count").innerHTML = "<%= current_user_cart_items_count %>";

<% if !@cart_item.nil? && @cart_item.invalid? %>
  alert('<%= purify_message(@cart_item.errors.full_messages.to_sentence) %>');
<%end%>
window.scrollTo(0, 0);

Kitty-Project-V2/app/views/cart_items/destroy.js.erb
document.getElementById("<%= @cart_item_id %>").remove();
document.getElementById("items-count").innerHTML = "<%= current_user_cart_items_count %>";
document.getElementById("total-quantities").innerHTML = '<%= current_user_cart_items_count %>';
document.getElementById("total").innerHTML = '<%=current_user_cart_total %>';

<% if current_user_cart_items_count == 0 %>
  itemsContainer = $('div#cart-items');
  itemsContainer.empty();
  itemsContainer.append('<%= j render 'cart_items/picture_indicating_empty_cart' %>')
<% end %>

Kitty-Project-V2/app/views/cart_items/index.html.erb
<div id='cart-items' class="container center_div">
  <% if @cart_items.count != 0 %>
    <div id="recap" class="texte-bienvenue text-center">
      <br>
      <h2>Voici un récapitulatif de votre commande</h2>
      <br>
    </div>
    <table class="table table-hover">
    <thead>
      <tr class="table-active">
        <th scope="col">PHOTO</th>
        <th scope="col">Titre</th>
        <th scope="col">Quantité</th>
        <th scope="col">Prix</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |x| %>
        <tr id='<%= x.id %>'>
          <%if x.item.image.attached? %>
            <td><%= image_tag x.item.image, alt: "Card image", width: 120, height: 80 %></td>
          <%else%>
            <th><p>=== Image ===</p></th>
          <%end%>
          <td><%= x.item.title %></td>
          <td><%= select_tag 'quantity', options_for_select((1..10), x.quantity), class: 'form-control form-control-sm w-auto' %></td>
          <td><%= x.item.price %>€</td>
          <td><%= link_to "Supprimer", cart_item_path(x.id), method: 'delete', :class => "btn btn-danger btn-sm", remote: true %></td>
        </tr>
      <%end%>
      <tr class="table-primary">
        <th>Total</th>
        <td></td>
        <td id="total-quantities" class='pl-5'><%= @total_quantities %></td>
        <td id="total"><%= @total %>€</td>
        <td></td>
      </tr>
    </tbody>
    </table>

    <br>
    <%= link_to 'Revenir à l\'accueil', root_path, class: 'btn btn-secondary text-decoration-none' %>
    <%= link_to "Passer Commande", new_order_path, :class => "btn btn-primary text-decoration-none" %>
    <br>
  <%else%>
    <%= render 'cart_items/picture_indicating_empty_cart' %>
  <%end%>
</div>

Kitty-Project-V2/app/views/cart_items/update.html.erb
<h6>Update Totals Values</h6>
<p id='total'><%= @total %></p>
<p id='total-quantities'><%= @total_quantities %></p>