agora/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users 
      
      resources :categories
      resources :cities
      resources :comments
      resources :likes
      resources :proposals
      resources :votes

      root to: "users#index"
  end
  
  root 'proposals#index'
  get '/contact', to: 'additional_views#contact', as: 'contact'
  get '/proposal_created', to: 'additional_views#proposal_created'
  get '/policy', to: 'additional_views#policy', as: 'policy'
  get '/legal', to: 'additional_views#legal', as: 'legal'
  get '/faq', to: 'additional_views#faq', as: 'faq'
  get '/mon_profil', to: 'users#show', as: 'mon_profil'
  get '/editer_mon_profil', to: 'users#edit', as: 'editer_mon_profil'

  resources :cities
  
  devise_for :users
  resources :users
  resources :users do
    resources :avatars, only: :create
  end

  resources :proposals
  resources :proposals do
    resources :votes, only: [:create, :destroy] 
    resources :pictures, only: :create
    resources :comments do
      resources :likes, only: [:create, :destroy, :edit]
      resources :comments, only: [:create, :destroy, :edit]
    end
  end

  resources :cities do
    resources :proposals do
      resources :votes, only: [:create, :destroy]
    end
  end
end

agora/app/models/proposal.rb
class Proposal < ApplicationRecord
  # Mailer config
  after_create :admin_receipt
  after_create :user_receipt
  after_update :validate_proposal
  #after_create :mail_vote
  
  # Relations
  belongs_to :city
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_many :votes

  # Active storage
  has_one_attached :picture

  # Validations
  validates :title, presence: true, length: { minimum: 3, maximum: 65 }
  validates :purpose, presence: true, length: { minimum: 10, maximum: 500 }
  validates :description, presence: true, length: { minimum: 30, maximum: 2000 }
  # validate :must_has_attachment

  # Instance methods
  
  def comments_count
    self.comments.count
  end
  
  def votes_count
    self.votes.count
  end
  
  def vote_of(user)
    self.votes.find_by(user: user)
  end
  
  def general_classification
    Proposal.all.sort { |p1, p2| p2.votes_count <=> p1.votes_count }.index(self) + 1
  end
  
  def category_classification
    self.category.proposals.sort { |p1, p2| p2.votes_count <=> p1.votes_count }.index(self) + 1
  end
  
  def on_line
    self.update(is_online: true)
  end
  
  def lifetime
    30 - ((Time.now - self.created_at).to_f / 1.day).floor
  end
  
  def is_expired?
    if(Time.now > (self.created_at + (60 * 60 * 24 * 30)))
      return true
    else
      return false
    end
  end

  def user_receipt
    ProposalMailer.info_user(self).deliver_now
  end

  def admin_receipt
    ProposalMailer.info_admin(self).deliver_now
  end

  private
  
  def validate_proposal
    if is_online?
      ProposalMailer.confirmation_proposal(self).deliver
    end
  end

  def must_has_attachment
    errors.add(:base, "Il faut associer une image à ta proposition !") unless self.picture.attached?
  end
end

agora/app/controllers/admin/proposals_controller.rb
module Admin
  class ProposalsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

agora/app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!, only: :new
  
  def index
    @paris = City.find(1)
    @proposal_paris= @paris.proposals.where(is_online: true).sort { |c1, c2| c2.votes_count <=> c1.votes_count }.first(5)
    
    @lyon = City.find(2)
    @proposal_lyon= @lyon.proposals.where(is_online: true).sort { |c1, c2| c2.votes_count <=> c1.votes_count }.first(5)
  end
  
  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = Proposal.new(permitted_proposal_params)

    if @proposal.save
      flash[:success] = 'Ta proposition a bien été enregistrée !'
      redirect_to proposal_created_path
    else
      flash[:alert] = @proposal.errors.full_messages.to_sentence
      render :new 
    end
  end
  
  def show
    @proposal = Proposal.find(permitted_proposal_id_param)
    @comments = @proposal.comments.order('created_at').reverse

    sort_value = params[:sortValue]
    tweet = params[:tweet]
    
    if sort_value # AJAX request comming from comments sorter, see public/comments_sorter.js
      case sort_value
      when '1'
        @comments = @proposal.comments.order('created_at').reverse
      when '2'
        @comments = @proposal.comments.sort { |c1, c2| c2.likes_count <=> c1.likes_count }
      when '3'
        @comments = @proposal.comments.sort { |c1, c2| c2.comments_count <=> c1.comments_count }
      end
    elsif tweet # AJAX request comming from tweet button, see public/tweet.js
      tweet(@proposal)
    end
  end
  
  def destroy
    @proposal = Proposal
  end

  private
  
  def permitted_proposal_id_param
    params.permit(:id).require(:id)
  end

  def permitted_proposal_params
    params.require(:proposal).permit(:title, :purpose, :category_id, :description, :picture).merge({:user => current_user, :city => current_user.city})
  end
end 

agora/app/helpers/proposals_helper.rb
module ProposalsHelper
  def tweet(proposal)
    title = @proposal.title
    first_name = @proposal.user.first_name
    last_name = @proposal.user.last_name
    tweet = "#projet_agora #{first_name} a proposé une initiative citoyenne dans sa ville intitulée : #{title}. Vous aussi ! vous pouvez le faire, cela est possible à travers notre site ! https://agora-prd.herokuapp.com/" 
    TwitterBot.new.tweet(tweet)
  end
end

agora/app/views/proposals/_proposal_comment.html.erb
<tr id='<%= x.id %>' class='proposal-comment'>
  <td>
    <b>
    <div class="avatar">
      <h5><b><i class="material-icons" style="font-size: 17px">face</i> <%= x.user.first_name %><%=" "%><%= x.user.last_name %>
      <%if x.user.id == x.proposal.user.id %>
        <span class="badge badge-primary">Initiateur</span>
      <%end%>
      </b><h5>
    </div>
    </b>
    <p class='text-wrap'><%= x.content %></p>
    <em class='text-muted'>Message posté le <%= x.created_at.to_formatted_s(:short )%> -</em>
    <%if user_signed_in?%>
      <%if current_user.id != x.user.id%>
        <%if Like.where(user_id: current_user.id, comment_id: x.id).any? %>
          <%= link_to "Aimé (#{Like.where(comment_id: x.id).count})", proposal_comment_like_path(proposal.id, x.id, Like.where(user_id: current_user.id, comment_id: x.id).first.id ), class: 'btn btn-success btn-xs',method: :delete, remote: true %>
        <%else%>
          <%= link_to "J'aime (#{Like.where(comment_id: x.id).count})", proposal_comment_likes_path(proposal.id, x.id), class: 'btn btn-primary btn-xs',method: :post, remote: true %>              
        <%end%>
      <%end%>
    <%end%>
    <%if user_signed_in?%>
      <%if current_user.id == x.user.id %>
        <%= link_to 'effacer',proposal_comment_path(proposal.id, x.id), class: 'btn btn-danger btn-xs', method: :delete, remote: true %> <span class='label label-success' style='font-weight: normal;'><%= x.likes.count %> AIMES</span>
      <%end%>
    <%end%>
    <div class = "container">
      <div class="row">
        <div id='comment-comments' class="col-xs-11 col-xs-offset-1">
          <% x.comments.order('created_at').reverse.each do |y| %>
            <%= render 'proposals/proposal_comment_comment', y: y, x: x, proposal: proposal  %>
          <%end%>
          <%if user_signed_in?%>
            <%=form_tag url_for(proposal_comment_comments_path(proposal.id, x.id)), remote: true do %> 
              <div class="form-group">
                <label>Répondre à <%= x.user.first_name %></label>
                <p id="comment-comment-content"><%= text_area_tag 'content',"", class: 'form-control border' %></p>
              </div>
              <%=submit_tag "Envoyer", {class: 'btn btn-primary btn-sm'}%>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </td> 
</tr>

agora/app/views/proposals/_proposal_comment_comment.html.erb
<div id='<%= y.id %>'>
  <br><b><i class="material-icons" style="font-size: 17px">face</i> <%=" " %><%= y.user.first_name %><%= " " %><%= y.user.last_name %></b><br><br>
  <p class='text-wrap'><%= y.content %></p>
  <small class='text-muted' style='font-style: italic;'>Message posté le <%= y.created_at.to_formatted_s(:short) %></small>
  <%if user_signed_in?%>
    <%if current_user.id == y.user.id %>
      <%= link_to 'effacer', proposal_comment_comment_path(proposal.id, x.id, y.id), class: 'btn btn-danger btn-xs',method: :delete, remote: true %>
    <%end%>
  <%end%>
  <br><br>
</div>

agora/app/views/proposals/_proposal_details.html.erb
<div id=<%= @proposal.id %> class="my-proposal container">
  <br>
  <h3><b>La proposition</b></h3>
  <br>
  <br>
  <div class="row">
    <div class="col-md-6 text-wrap text-justify">
      <div class="col">
        <div class="card card-product box">
          <%if @proposal.picture.attached?%>
            <div class="card-image" data-header-animation="true">
              <%= image_tag @proposal.picture, alt: 'Picture', style: "height: 50vh;" %>
            </div>
          <%else%>
            <div class="card-image" data-header-animation="true">
              <%= image_tag("home.jpg", style: "height: 50vh;")%>
            </div>
          <%end%>
          <div class="card-header">
            <h4 class="card-title"><%= @proposal.title %><br>
              <div>
                <%= link_to "#{@proposal.city.name}", city_path(@proposal.city.id), class: 'btn btn-primary btn-round btn-xs' %>
                <span class="badge badge-primary"><%= @proposal.category.name %></span>
              </div>
            </h4>
          </div>
          <div class="card-content">
            <ul class="nav nav-pills nav-pills-warnin">
              <li class="active primary">
                <a href="#pill1" data-toggle="tab">Problème adressé</a>
              </li>
              <li>
                <a href="#pill2" data-toggle="tab">Solution proposée</a>
              </li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="pill1">
                <%= @proposal.purpose %>
              </div>
              <div class="tab-pane" id="pill2">
                <%= @proposal.description %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if user_signed_in? %>
        <div class="col">
            <% if is_current_user_admin? %>
              <%= form_tag proposal_pictures_path(@proposal), multipart: true do %>
                <%= file_field_tag :picture %>
                <%= submit_tag "Mettre à jour" %>
              <% end %>
            <% end %>
        </div>
      <% end %>
    </div>
    <div class='col-md-1'></div>
    <div id='proposal-info' class="col-md-5">
      <div class="col">
        <div class="card card-testimonial box">
          <div class="card-content">
            <h5 class="text-muted" style="margin-bottom: 2px">Une proposition de</h5>
            <h6 class="card-title" style="margin-bottom: 0px"><%= @proposal.user.first_name %> <%= @proposal.user.last_name %></h6>
            <small class='text-muted' style='font-style: italic;'> Crée le <%= @proposal.created_at.strftime('%d/%m/%Y') %></small>
            <div>
              <% if is_current_user_owner_of?(@proposal) %>
                <button id="tweet-btn" class="btn btn-simple btn-twitter" style="margin-top: 0px; margin-bottom: 0px">
                  <i class="fa fa-twitter"></i> Tweeter ma proposition
                </button><br>
                <small class="text-muted">Besoin d'éditer votre proposition ? Ecrivez au support Agora !</small><br>
                <a class="btn btn-primary btn-xs" href="mailto: zeagoraproject@gmail.com" role="button">Ecrire au support</a>
              <% end %>
            </div>
          </div>
          <div class="footer">
            <% if @proposal.user.avatar.attached? %>
              <div class="card-avatar">
                <%= image_tag @proposal.user.avatar, alt: 'Picture', style: "width: 100%;height: auto;" %>
              </div>
            <% else %>
              <div class="card-avatar">
                <%= image_tag("avatar.png", style: "width:100%; height: auto;")%> 
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= render 'proposals/proposal_vote_informations', proposal: @proposal %>
    </div>
  </div>
</div>

agora/app/views/proposals/_proposal_vote_informations.html.erb
<div id='proposal-vote-info' class="col">
  <div class="card box" style="padding-bottom: 0px;">
    <div class="card-content text-center">
      <% unless is_current_user_owner_of?(proposal) %>
        <%if !proposal.is_expired? && proposal.votes_count < 5 %>
          <h5 class="text-muted" style='margin-bottom: 0px;'>Votez pour cette proposition</h5>
          <p class='text-muted' style='font-style: italic; margin-top: 0px'> Il reste : <%= proposal.lifetime %> jours pour voter</p>
          <%if user_signed_in?%>
            <%if proposal.city == current_user.city %>
              <%if proposal.vote_of(current_user)%>
                <%= link_to '<i class="material-icons" style="font-size: 19px">sentiment_satisfied_alt</i> A voté'.html_safe, proposal_vote_path(proposal.id, proposal.vote_of(current_user).id), id: 'del-vote-btn', :class => "btn btn-success", method: :delete, remote: true %>
              <%else%>
                <%= link_to '<i class="material-icons" style="font-size: 19px">how_to_vote</i> Je vote'.html_safe, proposal_votes_path(proposal.id), id:'add-vote-btn', :class => "btn btn-primary", method: :post, remote: true %>
              <%end%>
            <%else%>
              <p>Vous ne pouvez pas voter pour les propositions en dehors de votre ville !</p>
            <%end%> 
          <%else%>
            <p>Connectez-vous pour pouvoir voter !</p> 
          <%end%>
        <%else%>
          <%if proposal.is_expired? %>
            <div class="alert alert-warning">
              <p class="text-center">Expirée</p>
            </div>    
            <p class="text-muted text-center">Cette proposition n'a pas reçu le nombre de votes suffisant pour être validée avant la date limite.</p>
            <p class="text-muted text-center">Merci pour votre proposition <%= proposal.user.first_name %> !</p>    
          <%else%> 
            <div class="alert alert-info">
              <p class="text-center">Validée</p>
            </div>
            <p class="text-muted text-center">Cette proposition a reçu le nombre de votes minimum pour passer à l'action ! <%= proposal.user.first_name %> a été mis(e) en relation avec les votants.</p>
            <p class="text-muted text-center"> Bravo <%= proposal.user.first_name %> !</p> 
          <%end%>
        <%end%>
      <% else %>  
        <p class='text-muted' style='font-style: italic; margin-top: 0px'> Il reste : <%= proposal.lifetime %> jours avant l'expiration de la proposition</p>
      <% end %>
      <% if proposal.votes_count > 1 %>
        <h6 id='votes-count'><%= proposal.votes_count %> VOTES</h6>
      <% else %>
        <h6 id='votes-count'><%= proposal.votes_count %> VOTE </h6>
      <% end %>
    </div>
    <% unless proposal.votes_count == 0 %>
      <div class="card-footer" style="padding-top: 3px;  margin-bottom: 0px;">
        <div id='classification' class="price">
          <%= render 'proposals/classifications', proposal: proposal %>
        </div>
      </div>
    <% end %>
  </div>
</div>

agora/app/views/proposals/index.html.erb
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-6 order-md-1"> 
      <h1>Agissez ensemble pour changer votre ville</h1>
      <h4 class="text-white">Agora est une plateforme citoyenne vous permettant de proposer et de partager des initiatives locales</h4>
      <% if user_signed_in? %>
      <p><%= link_to 'Proposer mon idée', new_proposal_path, class: 'btn btn-primary btn-lg' %></p>
      <%else%>
      <p><a class="btn btn-primary btn-lg" href="/users/sign_in" role="button">Proposer mon idée</a></p>
      <%end%>
    </div>
    <div class="col-md-6 order-md-2 img-top">
      <%= image_tag("share.svg", style: "width:100%") %>
    </div>
  </div>
</div>
<br><br><br>
<div class="container">
  <h2 class="text-center"><b>Comment ça marche ?</b></h2>
  <br><br> 
  <div class="row featurette">
    <div class="col-md-7 order-md-1">
      <h2 class="featurette-heading">Proposez <i class="material-icons idea-icon" style="font-size: 33px">wb_incandescent</i></h2>
      <h5>Une idée vous inspire depuis longtemps ? Sur Agora, vous êtes libres de la montrer à vos concitoyens. Nous veillons à ce que les propositions les plus pertinentes soient présentées.</h5>
    </div>
    <div class="col-md-5 order-md-1 img-center">
      <%= image_tag("idea.svg", style: "width:65%;") %>
    </div>
  </div>
  <br><br>
  <div class="row featurette">
    <div class="col-md-5 col-lg-7 col-lg-push-5  ">
      <h2 class="featurette-heading">Votez  <i class="material-icons vote-icon" style="font-size: 33px">how_to_vote</i>
        <h5>Chaque jour, des citoyens comme vous réfléchissent à comment améliorer le quotidien de votre ville. Consultez et débattez des propositions ensemble !</h5>
    </div>
    <div class="col-md-7 col-lg-5 col-lg-pull-7 img-center">
          <%= image_tag("voting.svg", style: "width:65%") %>
      </div>    
    </div>
    <br><br>
    <div class="row featurette">
      <div class="col-md-7 order-md-1">
        <h2 class="featurette-heading">Agissez  <i class="material-icons group-icon" style="font-size: 33px">people</i></h2>
        <h5>Sur Agora, le système de vote permet de faire ressortir les meilleures propositions. Quand l'idée a reçu assez de votes positifs, nos équipes vous mettent en relation avec les citoyens soutenant votre projet. </h5>
      </div>
      <div class="col-md-5 order-md-2 img-center">
        <%= image_tag("group.svg", style: "width:70%") %>
      </div>
    </div>
  </div>
  <br><br>
  <h2 class="text-center"><b>Et après ?</b></h2>
<div class="container">
    <ul class="timeline">
        <li>
          <div class="timeline-badge primary"><i class="material-icons group-icon img-and-after">people</i></div>
          <div class="timeline-panel ">
            <div class="timeline-heading">
              <h4 class="timeline-title">Rassemblez-vous !</h4>
            </div>
            <div class="timeline-body">
              <h5>Le grand moment est arrivé ! À partir de 5 votes positifs, votre proposition est validée et nous vous mettons en relation avec toux ceux qui ont soutenu votre projet.</h5>
            </div>
          </div>
        </li>
        <li class="timeline-inverted">
          <div class="timeline-badge primary"><i class="material-icons group-icon img-and-after">add</i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Créez votre association</h4>
            </div>
            <div class="timeline-body">
              <h5>Selon la taille de votre projet, vous aurez besoin de créer une association à but non-lucratif.</h5>            
            </div>
          </div>
        </li>
        <li>
          <div class="timeline-badge primary"><i class="material-icons group-icon img-and-after">create</i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Montez votre dossier</h4>
            </div>
            <div class="timeline-body">
              <h5>Pour être prise en compte par la mairie, votre projet devra être présenté sous forme de dossier.</h5>
            </div>
          </div>
        </li>
        <li class="timeline-inverted">
          <div class="timeline-badge primary"><i class="material-icons group-icon img-and-after">grade</i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Rendez le monde meilleur </h4>
            </div>
            <div class="timeline-body">
              <h5>Votre idée a amélioré le quotidien de vos concitoyens et rendu votre ville encore plus belle. Bravo ! </h5>
            </div>
          </div>
        </li>
    </ul>
</div>
<br><br>
<h2 class="text-center"><b>Ils parlent de nous</b></h2>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-testimonial box zoom">
        <div class="icon">
          <i class="material-icons">format_quote</i>
        </div>
        <div class="card-content">
          <h5 class="card-description">
            Ce site est tout simplement génial ! Grâce à lui j'ai pu proposer mon idée et j'ai rencontré des citoyens soucieux de changer les choses. Encore merci à toute l'équipe d'Agora !
          </h5>
        </div>
        <div class="footer">
          <h4 class="card-title">Julien Jacquet</h4>
          <h6 class="category">@jjacquet</h6>
          <div class="card-avatar">
            <%= image_tag("julien.jpg", style: "width: 100%;height: auto") %>
          </div>
        </div>
      </div>
    </div> 
    <div class="col-md-4"> 
      <div class="card card-testimonial box zoom">
        <div class="icon">
          <i class="material-icons">format_quote</i>
        </div>
        <div class="card-content">
          <h5 class="card-description">
            Agora c'est la démocratie 2.0 ! On peut échanger, débattre et agir entre citoyens pour améliorer sa ville. Le site est très agréable à prendre en main et l'équipe est très réactive ! 
          </h5>
        </div>
        <div class="footer">
          <h4 class="card-title">Alexis Bernard</h4>
          <h6 class="category">@alexisbernard</h6>
          <div class="card-avatar">
            <%= image_tag("alexis.jpg", style: "width: 100%;height: auto") %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4"> 
      <div class="card card-testimonial box zoom">
        <div class="icon">
          <i class="material-icons">format_quote</i>
        </div>
        <div class="card-content">
          <h5 class="card-description">
            Avec Agora, j'ai trouvé des citoyens motivés et prêts à m'aider à réaliser mon projet ! J'ai pû débattre et agir avec eux pour améliorer ma ville. Merci Agora pour votre aide !
          </h5>
        </div>         
          <div class="footer">
            <h4 class="card-title">Marie Brun</h4>
            <h6 class="category">@mariebrun</h6>
          <div class="card-avatar">
            <%= image_tag("marie.jpg", style: "width: 100%;height: auto") %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>  
</div>
<br><br><br><br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h3 class="display-4 text-white"><b>Faites porter votre voix et changez votre ville !</b></h3>
      <h4 class="text-white"> Une idée inspirante ? Rendez la possible avec Agora !</h4>
      <% if user_signed_in? %>
      <p><%= link_to 'Proposer mon idée', new_proposal_path, class: 'btn btn-primary btn-lg' %></p>
      <%else%>
      <p><a class="btn btn-primary btn-lg" href="/users/sign_in" role="button">Proposer mon idée</a></p>
      <%end%>
    </div>
    <div class="col-md-5 img-group">
      <%= image_tag("community.svg", style: "width:90%") %>
    </div>
  </div>
</div>
<br><br><br>
<br>
<div class = "container">
  <h2 class="text-center"><b>Les meilleures propositions du moment</b></h2>
  <div class="col-md-6">
    <h3 class="text-center"><b>Paris</b></h3>
    <div class="card box">
      <div class="card-content">
      <div class="table-responsive">
        <table class="table datatables-s text-wrap" cellspacing="0" width="100%" style="width:100%">
          <thead>
            <tr>
              <th class="disabled-sorting"></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%@proposal_paris.each do |x|%>
            <tr>
              <td>
                <%if x.picture.attached?%>
                  <%= image_tag x.picture, alt: "Card image", width: 200, style: "height: auto" %>
                <%else%>
                  <%= image_tag("home.jpg", width: 200, style: "height: auto")%>
                <%end%>
              </td>
              <td>
                <p class="text-wrap"><%= x.title %></p>
                <p><a class="btn btn-primary btn-round btn-sm" href= "<%= proposal_path(x) %>" role="button">
                  <i class="material-icons" style="font-size: 15px">visibility</i> Voir la proposition
                </a>
                <span class="badge"><%= x.category.name %></span>
                </p>
              </td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <h3 class="text-center"><b>Lyon</b></h3>
    <div class="card box">
      <div class="card-content">
      <div class="table-responsive">
        <table class="table datatables-s text-wrap" cellspacing="0" width="100%" style="width:100%">
          <thead>
            <tr>
              <th class="disabled-sorting"></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%@proposal_lyon.each do |x|%>
            <tr>
              <td>
                <%if x.picture.attached?%>
                <%= image_tag Proposal.find(x.id).picture, alt: "Card image",  width: 170, style: "height: auto"%>
                <%else%>
                  <%= image_tag("home.jpg", width: 170, style: "height: auto")%>
                <%end%>                  
              </td>
              <td>
                <p class='text-wrap'><%= x.title %></p>
                <a class="btn btn-primary btn-round btn-sm" href= "/proposals/<%=x.id%>" role="button">
                  <i class="material-icons" style="font-size: 15px">visibility</i> Voir la proposition
                </a>
                <span class="badge badge-primary"><%= x.category.name %></span>
              </td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      </div>
    </div>
  </div>
</div>
<br><br><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3 class="display-4 text-white"><b>D'autres villes sont disponibles sur Agora ! N'hésitez pas à les consulter !</b></h3>
      <div class="dropdown">
        <button href="#" class="btn dropdown-toggle btn-primary btn-lg" data-toggle="dropdown" aria-expanded="true" >
          <i class="material-icons">home</i>  Les villes disponibles
          <b class="caret"></b>
        </button>
        <ul class="dropdown-menu">
          <% City.all.each do |x| %>
            <li><a href="cities/<%=x.id %>"><%= x.name %></a></li>
          <%end%>
        </ul>
      </div>
    </div>
    <div class="col-md-6 img-bottom">
      <%= image_tag("town.svg", style: "width:70%") %>
    </div>
  </div>
</div>
<br><br><br><br>
<div class = "container text-center">
  <h4 class="display-4 text-white"><b>Votre ville n'est pas encore disponible ? Dites-nous d'où vous venez !</b></h4>
  <p><a class="btn btn-primary " href="mailto: zeagoraproject@gmail.com" role="button"><i class="material-icons">mail</i>   Nous contacter</a></p>
</div>
</div>
</div>

agora/app/views/proposals/show.html.erb
<%= render 'proposals/proposal_details' %>
<%= render 'proposals/debate' %>